namespace WitcherAPI.Models {
    public enum AlchemyProductName {
        Unknown = 0,
        PotionSwallow = 100,
        PotionCat = 101,
        PotionWhiteGull = 102,
        PotionOriole = 103,
        PotionTawnyOwl = 104,
        PotionPetriFilter = 105,
        PotionOrca = 106,
        PotionBlizzard = 107,
        PotionRock = 108,
        PotionThunderBolt = 109,
        OilHangmanVenom = 200,
        OilAntiVampire = 201,
        OilAntiInsectoid = 202,
        OilAntiSpecter = 203,
        OilAntiBeasts = 204,
        OilAntiCursed = 205,
        OilAntiOgroid = 206,
        OilAntiRelict = 207,
        OilAntiHybrid = 208,
        OilAntiDraconid = 209,
        OilAntiElemental = 210,
        OilAntiNecrophage = 211,
        BombSamum = 300,
        BombDancingStar = 301,
        BombSpark = 302
    }
}